-- Add face_rating column to profiles table
-- This stores the Gemini AI attractiveness rating (1-15)

ALTER TABLE public.profiles
ADD COLUMN face_rating INTEGER CHECK (face_rating >= 1 AND face_rating <= 15);

-- Add index for potential filtering/sorting by rating
CREATE INDEX idx_profiles_face_rating ON public.profiles(face_rating);

-- Add comment for documentation
COMMENT ON COLUMN public.profiles.face_rating IS 'Attractiveness rating from 1-15 generated by Gemini AI during signup';
